server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/permission?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    view:
      suffix: .jsp
      prefix: ""
user:
  initPassword: 123456
auth:
  whiteList:
    - ${auth.noAuthUrl}
    - /user/login
    - /js/**
    - /css/**
    - /bootstrap3.3.5/**
    - /assets/**
    - /ztree/**
    - /signin.jsp
    - /user/**
    - /pages/noAuth.jsp
  noAuthUrl: /pages/noAuth.jsp

